source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target ’TZTV’ do

pod 'ReactiveCocoa','~> 2.5'
pod 'PureLayout', '~> 3.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'
pod 'Masonry', '~> 1.0.2'

pod 'PLMediaStreamingKit', '~> 2.0.0'
pod 'PLPlayerKit', '~> 2.2.2'

end
